### ISSUE TITLE
Code style + tslint enforcement

### ISSUE THREAD

**Issue by basdp** [CoronApp-project/socialdistancing-ionic#18]
We need a code style plus a tslint file for enforcement. 

There are nice ways of enforcing it in git hooks, so we can't commit code that doesn't comply with our code style.

My suggestion would be following the the Angular style guide:
https://angular.io/guide/styleguide

But other suggestions can be done, our only requirement is that we have a consistent style.

**_To the assignees_: please have a discussion here in the comments about the options, or if you agree just let it know.**

I have put a hard deadline on the decision on 12pm today, 2020-03-25. We need to have this enforced ASAP.

**Comment by Mr-Jin** [comment]
Since we are using Ionic; Angular I think that it would be only logical to follow their Code Style, also factoring in the given time for the MVP. 

So I agree with your proposal.

**Comment by basdp** [comment]
This issue is now closed. We follow the official Angular styleguide. The .tslint file that comes with Ionic is already enforcing that.

I decided not to go with Git pre-commit hooks, because the internets say that it's very fragile. Enforcement will be done later via CI/CD.
